config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/home', to: 'pages#home'
  get '/wakemydyno.txt', to: 'pages#dyno'

  resources :recipes do
    member do
      post 'like'
    end
  end

  resources :chefs, except: [:new, :destroy]
  get '/register', to: 'chefs#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :recipes
  has_many :likes
  before_save { self.email = email.downcase }
  validates :chefname, presence: true, length: { minimum: 3, maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  mount_uploader :picture, PictureUploader
  validate :picture_size


  has_secure_password

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 25 }
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :chef
  belongs_to :recipe

  validates_uniqueness_of :chef, scope: :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  has_many :likes, dependent: :destroy
  has_many :recipe_styles, dependent: :destroy
  has_many :styles, through: :recipe_styles
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  validates :chef_id, presence: true
  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :summary, presence: true, length: { minimum: 5, maximum: 150 }
  validates :description, presence: true, length: { minimum: 15, maximum: 2500 }
  mount_uploader :picture, PictureUploader
  validate :picture_size
  default_scope -> { order(updated_at: :desc) }

  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end


  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe_style.rb
class RecipeStyle < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :style
end

app/models/style.rb
class Style < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 25 }
  has_many :recipe_styles
  has_many :recipes, through: :recipe_styles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You musted be logged in to perform that action"
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]

  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 3)
  end

  def new
    @chef = Chef.new
  end

  def create
    @chef = Chef.new(chef_params)
    if @chef.save
      flash[:success] = "Account Successfully Created"
      session[:chef_id] = @chef.id
      redirect_to recipes_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @chef.update(chef_params)
      flash[:success] = "Profile Successfully Updated"
      redirect_to chef_path(@chef)
    else
      render :edit
    end
  end

  def show
    @recipes = @chef.recipes.paginate(page: params[:page], per_page: 3)
  end

  private

  def chef_params
    params.require(:chef).permit(:chefname, :email, :password, :picture)
  end

  def set_chef
    @chef = Chef.find(params[:id])
  end

  def require_same_user
    if current_user != @chef
    flash[:danger] = "You can only edit your own profile"
    redirect_to root_path
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :require_user, except: [:show]


  def show
    @ingredient = Ingredient.find(params[:id])
    @recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 4)
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(style_params)
    if @ingredient.save
      flash[:success] = "Ingredient Successfully Created"
      redirect_to recipes_path
    else
      render 'new'
    end

  end

  private

  def style_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to recipes_path if logged_in?
  end

  def dyno
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_recipe, only: [:edit, :update, :show, :like]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 4)
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_user
    if  @recipe.save
      flash[:success] = "Your recipe was created successfully"
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe updated successfully"
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe Deleted"
    redirect_to recipes_path
  end

  def like
    like = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
    if like.valid?
      redirect_back(fallback_location: recipe_path(@recipe)) and return
    else
      flash[:danger] = "You can only like/dislike a recipe once"
    end
    redirect_back(fallback_location: recipe_path(@recipe)) and return
  end

  private

    def recipe_params
      params.require(:recipe).permit(:name, :summary, :description, :picture, style_ids: [], ingredient_ids: [])
    end

    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def require_same_user
      if current_user != @recipe.chef and !current_user.admin?
      flash[:danger] = "You can only edit your own recipes"
      redirect_to recipes_path
    end
  end

  def admin_user
    redirect_to recipe_path unless current_user.admin?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    chef = Chef.find_by(email: params[:email])
    if chef && chef.authenticate(params[:password])
      session[:chef_id] = chef.id
      flash[:sucess] = "Logged in!"
      redirect_to recipes_path
    else
      flash.now[:danger] = "Your email or password does not match"
    end
  end

  def destroy
    session[:chef_id] = nil
    flash[:success] = "Logged out!"
    redirect_to root_path
  end

end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :require_user, except: [:show]


  def show
    @style = Style.find(params[:id])
    @recipes = @style.recipes.paginate(page: params[:page], per_page: 4)
  end

  def new
    @style = Style.new
  end

  def create
    @style = Style.new(style_params)
    if @style.save
      flash[:success] = "Style Successfully Created"
      redirect_to recipes_path
    else
      render 'new'
    end

  end

  private

  def style_params
    params.require(:style).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(chef, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url,  alt: chef.chefname, class: "gravatar")
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for @chef do |f| %>
    <%= f.label :name %>
    <%= f.text_field :chefname %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <span class="picture">
      <%= f.label :avatar %>
      <%= f.file_field :picture, accept: 'image/jpeg, image/png, image/gif, image/jpg' %>
    </span>

    <%= f.submit(@chef.new_record? ? 'Register' : 'Edit Profile', class: 'btn btn-success') %>
    <% end %>
  </div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title', title: "Edit Profile" %>
<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "All Chefs" %>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= will_paginate %>
  </div>
</div>

<% @chefs.each do |chef| %>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= link_to image_tag('default.png', size: 200), chef_path(chef) %>
    <h5>Chef Name: <%= chef.chefname %></h5>
  </div>
</div>

  <% end %>

app/views/chefs/new.html.erb
<%= render 'shared/page_title', title: "Sign Up" %>
<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title: "Chef: " + @chef.chefname %>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <% if @chef.picture? %>
    <%= link_to image_tag(@chef.picture, class: 'gravatar', size: 250) %>
    <% else %>
    <%= link_to image_tag('default.png', size: 250) %>
    <% end %>    <hr/>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <h3><em><%= @chef.chefname %>'s Recipes: </em></h3>
    <%= will_paginate @recipes %>
  </div>
</div>

<% @recipes.each do |recipe| %>
  <div class="row">
    <div class="col-lg-6 well col-lg-offset-3">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <p>
        <span class="quiet"><small>created: <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
        <span class="quiet"><small>updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
      </p>
      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp; <%= recipe.thumbs_up_total %>
        <% end %> &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp; <%= recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/ingredients/_ingredient.html.erb
<span class="quiet"><%= link_to ingredient.name, ingredient_path(ingredient) %>, </span>

app/views/ingredients/new.html.erb
<%= render 'shared/page_title', title: "Create a New Ingredient" %>

<%= render 'shared/errors', obj: @ingredient %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for @ingredient do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit 'Create Ingredient', class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/ingredients/show.html.erb
<%= render 'shared/page_title', title: " Recipes with : " + @ingredient.name %>

<%= will_paginate @recipes %>

<% @ingredient.recipes.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <% if recipe.chef.picture? %>
        <%= link_to image_tag(recipe.chef.picture, size: 100), chef_path(recipe.chef) %>
        <% else %>
        <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
        <% end %>
        <h5>Chef name: <%= recipe.chef.chefname %></h5>
      </section>
    </div>
    <div class="col-lg-6 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <p>Style: <%= render recipe.styles %>
      <p>Ingredients: <%= render recipe.ingredients %></p>
      <p>
        <span class="quiet"><small>created: <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
        <span class="quiet"><small>updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
      </p>
      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp; <%= recipe.thumbs_up_total %>
        <% end %> &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp; <%= recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <%= image_tag(recipe.picture.url, size: "220x150", class: "gravatar") if recipe.picture? %>
    </div>
  </div>
</hr>
<% end %>

<%= will_paginate @recipes %>

app/views/layouts/_footer.html.erb
<footer>
  <p>&copy; Recipes on Rails</p>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %>
      <a class="close" data-dismiss="alert">&#215;</a>
    </div>
      <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "Recipes on Rails", root_path, class: "btn btn-lg btn-success", id: "logo" %>>
    <div class="nav_ul_item">
      <%= link_to "All Recipes", recipes_path, class: "btn btn-default btn-warning" %>
    </div>
    <ul class="nav_ul_item">
      <li class="dropdown">
        <%= link_to '#', class: 'btn btn-default btn-info dropdown-toggle', "data-toggle" => "dropdown" do %>
          Browse by Style <b class="caret"></b>
        <% end %>
        <ul class="dropdown-menu">
          <% Style.all.each do |style| %>
          <li><%= link_to style.name, style_path(style) %></li>
          <% end %>
          <% if logged_in? %>
            <li class='divider'></li>
            <li>
              <%= link_to(new_style_path) do %>
              New Style
              <% end %>
            </li>
          <% end %>
        </ul>
      </li>
    </ul>
    <!-- <ul class="nav_ul_item">
      <li class="dropdown">
        <%= link_to '#', class: 'btn btn-default btn-info dropdown-toggle', "data-toggle" => "dropdown" do %>
          Browse by Ingredients <b class="caret"></b>
        <% end %>
        <ul class="dropdown-menu">
          <% Ingredient.all.each do |ingredient| %>
          <li><%= link_to ingredient.name, ingredient_path(ingredient) %></li>
          <% end %>
          <% if logged_in? %>
            <li class='divider'></li>
            <li>
              <%= link_to(new_ingredient_path) do %>
              New Ingredient
              <% end %>
            </li>
          <% end %>
        </ul>
      </li>
    </ul> -->

    <% if logged_in? %>
    <div class="nav_item">
      <%= link_to "New Recipe", new_recipe_path, class: "btn btn-default btn-warning" %>
    </div>
    <ul class="nav_item">
      <li class="dropdown">
        <%= link_to '#', class: 'btn btn-default btn-danger dropdown-toggle userbutton', "data-toggle" => "dropdown" do %>
          <% if current_user.admin? %>[Admin] <% end %> <%= current_user.chefname %> <b class="caret"></b>
        <% end %>
        <ul class="dropdown-menu">
          <li><%= link_to "View Profile", chef_path(current_user) %></li>
          <li><%= link_to "Edit Profile", edit_chef_path(current_user) %></li>
          <li class="divider"></li>
          <li><%= link_to "Logout", logout_path %></li>
        </ul>
      </li>
    </ul>
    <% else %>
    <div class="nav_item">
    <%= link_to "Log In", login_path, class: "btn btn-default btn-success" %>
    <%= link_to "Register", register_path, class:"btn btn-large btn-success"%>
  </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipes on Rails</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navigation' %>

  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>

    <%= render 'layouts/footer' %>

  </div>
</body>
</html>

app/views/pages/home.html.erb
<div class="container">
<%= render 'shared/page_title', title: "Welcome to Recipes on Rails" %>
  <h2>Sign up to start adding recipes</h2>
  <h2><%= link_to "Sign up now!", register_path, class:"btn btn-large btn-success"%></h2>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <%= link_to image_tag("food.jpg", :alt => "Slide1"), {:class => "img-responsive", :alt => "Responsive image", :style => "width: 100%"} %>
      </div>

      <div class="item">
        <%= link_to image_tag("food2.jpg", :alt => "Slide1"), {:class => "img-responsive", :alt => "Responsive image", :style => "width: 100%"} %>
      </div>

      <div class="item">
        <%= link_to image_tag("food3.jpg", :alt => "Slide1"), {:class => "img-responsive", :alt => "Responsive image", :style => "width: 100%"} %>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for(@recipe, html: { multipart: true }) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :summary %>
    <%= f.text_field :summary %>

    <%= f.label :description, 'Ingredients & Instructions' %>
    <%= f.text_area :description, rows: 10 %>

    <strong>Styles:</strong>
    <%= f.collection_check_boxes :style_ids, Style.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
    <br><br>
    <!-- <strong>Ingredients:</strong>
    <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cbi| %>
      <% cbi.label(class: "checkbox-inline input_checkbox") {cbi.check_box(class: "checkbox") + cbi.text} %>
    <% end %> -->
    <br><br>
    <span class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg, image/png, image/gif, image/jpg' %>
    </span>

    <%= f.submit(@recipe.new_record? ? 'Create Recipe' : 'Confirm Changes', class: 'btn btn-success') %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
$('#recipe_picture').bind('change', function() {
  size_in_megabytes = this.files[0].size/1024/1024;
  if (size_in_megabytes > 5) {
    alert("Maximun file size is 5MB. Please choose a smaller file");
  }
});
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit Recipe" %>
<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes" %>

<%= will_paginate %>

<% @recipes.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <% if recipe.chef.picture? %>
        <%= link_to image_tag(recipe.chef.picture, size: 100), chef_path(recipe.chef) %>
        <% else %>
        <%= link_to image_tag('default.png', size: 100), chef_path(recipe.chef) %>
        <% end %>
        <h5>Chef name: <%= recipe.chef.chefname %></h5>
      </section>
    </div>
    <div class="col-lg-6 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <% if recipe.styles.any? %>
      <p>Style: <%= render recipe.styles %>
      <% end %>
      <!-- <% if recipe.ingredients.any? %>
      <p>Ingredients: <%= render recipe.ingredients %></p>
      <% end %> -->
      <p>
        <span class="quiet"><small>created: <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
        <span class="quiet"><small>updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
      </p>
      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp; <%= recipe.thumbs_up_total %>
        <% end %> &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp; <%= recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <%= image_tag(recipe.picture.url, size: "220x150", class: "gravatar indexpic") if recipe.picture? %>
    </div>
  </div>
<hr/>
<% end %>

<%= will_paginate %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a New Recipe" %>
<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>
<div class="row">
  <div class="col-md-4 pull-right center">

    <% if @recipe.chef.picture? %>
    <%= link_to image_tag(@recipe.chef.picture, class: 'gravatar showpic', size: 250), chef_path(@recipe.chef) %>
    <% else %>
    <%= link_to image_tag('default.png', class: 'gravatar showpic', size: 250), chef_path(@recipe.chef) %>
    <% end %>

    <p>
      <h5>Brought to you by: <%= @recipe.chef.chefname %></h5>
    </p>
  </div>

  <div class="col-md-8">
    <% if logged_in? && (@recipe.chef = current_user || current_user.admin?) %>
    <%= link_to "Delete Recipe", @recipe, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger pull-right' %>
    <%= link_to 'Edit Recipe', edit_recipe_path(@recipe), class: 'btn btn-success pull-right' %>
    <% end %>

    <h3><%= @recipe.summary %></h3><hr />

    <div class="well">
      <% if @recipe.styles.any? %>
      <p>Style: <%= render @recipe.styles %>
        <% end %>
        <!-- <% if @recipe.ingredients.any? %>
      <p>Ingredients: <%= render @recipe.ingredients %></p>
      <% end %> -->
      <p><strong>Ingredients & Instructions:</strong></p>
      <%= simple_format(@recipe.description) %>
      <div class="pull-right">
        <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp; <%= @recipe.thumbs_up_total %>
        <% end %> &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp; <%= @recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<h5><%= link_to 'Return to Recipes Listing', recipes_path, class: "btn btn-warning btn-small" %></h5>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="alert alert-danger col-md-8 col-md-offset-2">
    <h5>Please corrent the following errors:</h5>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/shared/_page_title.html.erb
<p><h1 class ="title"><%= title %></h1><hr/></p>

app/views/styles/_style.html.erb
<span class="quiet"><%= link_to style.name, style_path(style) %>, </span>

app/views/styles/new.html.erb
<%= render 'shared/page_title', title: "Create a New Style" %>

<%= render 'shared/errors', obj: @style %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for @style do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit 'Create Style', class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/styles/show.html.erb
<%= render 'shared/page_title', title: @style.name + " Recipes" %>

<%= will_paginate @recipes %>

<% @style.recipes.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <% if recipe.chef.picture? %>
        <%= link_to image_tag(recipe.chef.picture, size: 100), chef_path(recipe.chef) %>
        <% else %>
        <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
        <% end %>
        <h5>Chef name: <%= recipe.chef.chefname %></h5>
      </section>
    </div>
    <div class="col-lg-6 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <p>Style: <%= render recipe.styles %>
      <p>Ingredients: <%= render recipe.ingredients %></p>
      <p>
        <span class="quiet"><small>created: <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
        <span class="quiet"><small>updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
      </p>
      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp; <%= recipe.thumbs_up_total %>
        <% end %> &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp; <%= recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <%= image_tag(recipe.picture.url, size: "220x150", class: "gravatar") if recipe.picture? %>
    </div>
  </div>
</hr>
<% end %>

<%= will_paginate @recipes %>